name: 'Setup build environment'
description: 'Sets up the build environment: checks out code, installs Bun, caches dependencies, and runs bun install.'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
